In [1]:
# import packages
from deabook import MB
from deabook.constant import RTS_CRS,RTS_VRS1
import pandas as pd

# import all data (including the contextual varibale)
from pandas.api.types import CategoricalDtype
cat_size_order = CategoricalDtype(
    ['OE',	'TE',	'PIAE',	'NPIAE',	'NPOAE'], 
    ordered=True
)

data = pd.read_excel(r"../../data\power plant data.xlsx").query('year>2014').reset_index(drop=True)
data.columns = ['province', 'K', 'L', 'F', 'E', 'CO2', 'year', '省份']
dmuname = '省份'

yearid = data[['year',dmuname,'CO2']]
yearid

    year   省份       CO2
0   2015   北京   1592.34
1   2015   天津   5115.45
2   2015   河北  24012.84
3   2015   山西  22033.72
4   2015  内蒙古  39424.28
..   ...  ...       ...
85  2017   陕西  12534.67
86  2017   甘肃   6443.05
87  2017   青海   1428.51
88  2017   宁夏  11625.40
89  2017   新疆  22738.06

[90 rows x 3 columns]

In [2]:
data

          province     K      L         F        E       CO2  year   省份
0          Beijing   965   5.76    908.31   412.53   1592.34  2015   北京
1          Tianjin  1283   3.27   1920.51   635.88   5115.45  2015   天津
2            Hebei  4350  14.45   7461.84  2288.70  24012.84  2015   河北
3           Shanxi  5940   8.41   7960.77  2318.60  22033.72  2015   山西
4   Inner Mongolia  7263  11.92  14092.70  3421.93  39424.28  2015  内蒙古
..             ...   ...    ...       ...      ...       ...   ...  ...
85         Shaanxi  3144   9.78   4601.91  1586.05  12534.67  2017   陕西
86           Gansu  2059  11.09   2323.90   713.91   6443.05  2017   甘肃
87         Qinghai   399   2.12    538.12   161.19   1428.51  2017   青海
88         Ningxia  2583   2.91   4163.78  1167.76  11625.40  2017   宁夏
89        Xinjiang  5207   8.21   8219.75  2368.88  22738.06  2017   新疆

[90 rows x 8 columns]

In [3]:
yearid[dmuname].unique()

array(['北京', '天津', '河北', '山西', '内蒙古', '辽宁', '吉林', '黑龙江', '上海', '江苏', '浙江',
       '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南', '重庆',
       '四川', '贵州', '云南', '陕西', '甘肃', '青海', '宁夏', '新疆'], dtype=object)

In [4]:
data[['K','L','F','E','CO2']].describe().T.to_markdown("table7.1.md")

In [5]:
ssss

NameError: name 'ssss' is not defined

## MB

In [6]:
sx = data['CO2'].sum()/data['F'].sum()
sy = 0
# define and solve the test_DEAt model
def MB_CRSL1():

    # model = DEA.DEA(data,sent = "K L E=Y:CO2",  orient="L", rts=RTS_VRS, baseindex=None,refindex=None)
    model =MB.MB(data,sent = "K L+F=E:CO2", sx=[[0,0,sx]], sy=[[sy]], \
                    rts=RTS_CRS,baseindex=None,refindex=None,level=1)
    res,info =  model.optimize("mosek","1")
    return res
MB_CRSL1 = MB_CRSL1()
MB_CRSL1

    optimization_status           obj  best of Undesirable
0                   1.0   1592.340000          1592.340000
1                   1.0   4752.262658          4752.262658
2                   1.0  21822.691755         21822.691755
3                   1.0  17904.474658         17904.474658
4                   1.0  27513.058805         27513.058805
..                  ...           ...                  ...
85                  1.0  12046.319224         12046.319224
86                  1.0   4295.377920          4295.377920
87                  1.0    939.261133           939.261133
88                  1.0   9540.124728          9540.124728
89                  1.0  18670.359251         18670.359251

[90 rows x 3 columns]

In [7]:
sx = data['CO2'].sum()/data['F'].sum()
sy = 0
# define and solve the test_DEAt model
def MB_CRSL2():

    # model = DEA.DEA(data,sent = "K L E=Y:CO2",  orient="L", rts=RTS_VRS, baseindex=None,refindex=None)
    model =MB.MB(data,sent = "K L+F=E:CO2", sx=[[0,0,sx]], sy=[[sy]], \
                    rts=RTS_CRS,baseindex=None,refindex=None,level=2)
    res,info =  model.optimize("mosek","1")
    return res
MB_CRSL2 = MB_CRSL2()
MB_CRSL2

    optimization_status           obj  best of Undesirable
0                   1.0   1592.340000          1592.340000
1                   1.0   4752.262658          4752.262658
2                   1.0  21822.691755         21822.691755
3                   1.0  17904.474658         17904.474658
4                   1.0  27513.058805         27513.058805
..                  ...           ...                  ...
85                  1.0  12046.319224         12046.319224
86                  1.0   4295.377920          4295.377920
87                  1.0    939.261133           939.261133
88                  1.0   9540.124728          9540.124728
89                  1.0  18670.359251         18670.359251

[90 rows x 3 columns]

In [8]:
sx = data['CO2'].sum()/data['F'].sum()
sy = 0
# define and solve the test_DEAt model
def MB_CRSL3():

    # model = DEA.DEA(data,sent = "K L E=Y:CO2",  orient="L", rts=RTS_VRS, baseindex=None,refindex=None)
    model =MB.MB(data,sent = "K L+F=E:CO2", sx=[[0,0,sx]], sy=[[sy]], \
                    rts=RTS_CRS,baseindex=None,refindex=None,level=3)
    res,info =  model.optimize("mosek","1")
    return res
MB_CRSL3 = MB_CRSL3()
MB_CRSL3

    optimization_status           obj  best of Undesirable
0                   1.0   1560.103792          1560.103792
1                   1.0   3617.484002          3617.484002
2                   1.0  17092.312335         17092.312335
3                   1.0  13905.609612         13905.609612
4                   1.0  20906.091263         20906.091263
..                  ...           ...                  ...
85                  1.0   9322.480651          9322.480651
86                  1.0   4294.522427          4294.522427
87                  1.0    906.062583           906.062583
88                  1.0   7102.157964          7102.157964
89                  1.0  14193.396531         14193.396531

[90 rows x 3 columns]

In [9]:
sx = data['CO2'].sum()/data['F'].sum()
sy = 0
# define and solve the test_DEAt model
def MB_CRSL4():

    # model = DEA.DEA(data,sent = "K L E=Y:CO2",  orient="L", rts=RTS_VRS, baseindex=None,refindex=None)
    model =MB.MB(data,sent = "K L+F=E:CO2", sx=[[0,0,sx]], sy=[[sy]], \
                    rts=RTS_CRS,baseindex=None,refindex=None,level=4)
    res,info =  model.optimize("mosek","1")
    return res
MB_CRSL4 = MB_CRSL4()
MB_CRSL4

    optimization_status          obj  best of Undesirable
0                   1.0    -0.000000            -0.000000
1                   1.0    -0.000000            -0.000000
2                   1.0  3247.575108          3247.575108
3                   1.0    -0.000000            -0.000000
4                   1.0   206.252201           206.252201
..                  ...          ...                  ...
85                  1.0    -0.000000            -0.000000
86                  1.0    -0.000000            -0.000000
87                  1.0    -0.000000            -0.000000
88                  1.0    38.178262            38.178262
89                  1.0    -0.000000            -0.000000

[90 rows x 3 columns]

In [10]:
MB_CRSL1 = MB_CRSL1.drop(columns = ['optimization_status','obj'])
MB_CRSL2 = MB_CRSL2.drop(columns = ['optimization_status','obj'])
MB_CRSL3 = MB_CRSL3.drop(columns = ['optimization_status','obj'])
MB_CRSL4 = MB_CRSL4.drop(columns = ['optimization_status','obj'])

MB_CRSL1 = MB_CRSL1.rename(columns = {'best of Undesirable':'B1'})
MB_CRSL2 = MB_CRSL2.rename(columns = {'best of Undesirable':'B2'})
MB_CRSL3 = MB_CRSL3.rename(columns = {'best of Undesirable':'B3'})
MB_CRSL4 = MB_CRSL4.rename(columns = {'best of Undesirable':'B4'})

MB_CRS = pd.concat([yearid,MB_CRSL1],axis=1)
MB_CRS = pd.concat([MB_CRS,MB_CRSL2],axis=1)
MB_CRS = pd.concat([MB_CRS,MB_CRSL3],axis=1)
MB_CRS = pd.concat([MB_CRS,MB_CRSL4],axis=1)

In [11]:
MB_CRS['OE'] = MB_CRS['B4'] / MB_CRS['CO2'] 
MB_CRS['TE'] = MB_CRS['B1'] / MB_CRS['CO2'] 
MB_CRS['PIAE'] = MB_CRS['B2'] / MB_CRS['B1'] 
MB_CRS['NPIAE'] = MB_CRS['B3'] / MB_CRS['B2'] 
MB_CRS['NPOAE'] = MB_CRS['B4'] / MB_CRS['B3'] 


cat_size_order

CategoricalDtype(categories=['OE', 'TE', 'PIAE', 'NPIAE', 'NPOAE'], ordered=True, categories_dtype=object)

In [12]:
MB_CRS.query('year==2017')#.sort_values('MQ')

,year,省份,CO2,B1,B2,B3,B4,OE,TE,PIAE,NPIAE,NPOAE
60,2017,北京,1328.24,1328.240000,1328.240000,1328.240000,-0.000000,-0.000000,1.000000,1.0,1.000000,-0.000000
61,2017,天津,4927.63,4481.460618,4481.460618,3463.065632,-0.000000,-0.000000,0.909456,1.0,0.772754,-0.000000
62,2017,河北,26802.07,26802.070000,26802.070000,19424.925127,4450.323776,0.166044,1.000000,1.0,0.724755,0.229104
63,2017,山西,25022.67,19300.733112,19300.733112,14923.800994,-0.000000,-0.000000,0.771330,1.0,0.773225,-0.000000
64,2017,内蒙古,44495.77,30401.168911,30401.168911,23005.821700,319.434945,0.007179,0.683237,1.0,0.756741,0.013885
65,2017,辽宁,16003.93,10956.516576,10956.516576,9107.111712,584.374469,0.036514,0.684614,1.0,0.831205,0.064167
66,2017,吉林,7850.81,3681.375507,3681.375507,3663.071899,-0.000000,-0.000000,0.468917,1.0,0.995028,-0.000000
67,2017,黑龙江,8633.52,4684.080062,4684.080062,4683.769285,-0.000000,-0.000000,0.542546,1.0,0.999934,-0.000000
68,2017,上海,7138.07,6735.574188,6735.574188,5113.729785,-0.000000,-0.000000,0.943613,1.0,0.759212,-0.000000
69,2017,江苏,37054.37,37054.370000,37054.370000,26464.926920,-0.000000,-0.000000,1.000000,1.0,0.714219,-0.000000
70,2017,浙江,18898.32,18898.320000,18898.320000,14316.084345,-0.000000,-0.000000,1.000000,1.0,0.757532,-0.000000
71,2017,安徽,19597.66,18132.683425,18132.683425,13698.307404,-0.000000,-0.000000,0.925247,1.0,0.755448,-0.000000
72,2017,福建,9849.10,8156.149187,8156.149187,6579.012378,-0.000000,-0.000000,0.828111,1.0,0.806632,-0.000000
73,2017,江西,7906.73,6820.703591,6820.703591,5470.500195,-0.000000,-0.000000,0.862645,1.0,0.802043,-0.000000
74,2017,山东,40573.07,39029.399282,39029.399282,30085.889132,361.171158,0.008902,0.961953,1.0,0.770852,0.012005
75,2017,河南,22980.15,18183.205951,18183.205951,15462.616083,-0.000000,-0.000000,0.791257,1.0,0.850379,-0.000000
76,2017,湖北,8797.52,6836.907939,6836.907939,6377.769338,67.879268,0.007716,0.777140,1.0,0.932844,0.010643
77,2017,湖南,7479.18,5492.551154,5492.551154,5491.847059,734.053235,0.098146,0.734379,1.0,0.999872,0.133662
78,2017,广东,26647.72,22769.946482,22769.946482,18487.390011,-0.000000,-0.000000,0.854480,1.0,0.811921,-0.000000
79,2017,广西,6081.24,3755.891438,3755.891438,3755.570114,21.114515,0.003472,0.617619,1.0,0.999914,0.005622
80,2017,海南,1714.95,1279.486695,1279.486695,1051.374108,-0.000000,-0.000000,0.746078,1.0,0.821716,-0.000000
81,2017,重庆,4065.53,3020.446598,3020.446598,2616.797399,-0.000000,-0.000000,0.742940,1.0,0.866361,-0.000000
82,2017,四川,3851.80,2695.586367,2695.586367,2695.586367,556.781044,0.144551,0.699825,1.0,1.000000,0.206553
83,2017,贵州,10139.82,8473.096626,8473.096626,6934.863734,-0.000000,-0.000000,0.835626,1.0,0.818457,-0.000000
84,2017,云南,3127.40,1488.279677,1488.279677,1488.279677,38.535401,0.012322,0.475884,1.0,1.000000,0.025893
85,2017,陕西,12534.67,12046.319224,12046.319224,9322.480651,-0.000000,-0.000000,0.961040,1.0,0.773886,-0.000000
86,2017,甘肃,6443.05,4295.377920,4295.377920,4294.522427,-0.000000,-0.000000,0.666668,1.0,0.999801,-0.000000
87,2017,青海,1428.51,939.261133,939.261133,906.062583,-0.000000,-0.000000,0.657511,1.0,0.964655,-0.000000
88,2017,宁夏,11625.40,9540.124728,9540.124728,7102.157964,38.178262,0.003284,0.820628,1.0,0.744451,0.005376
89,2017,新疆,22738.06,18670.359251,18670.359251,14193.396531,-0.000000,-0.000000,0.821106,1.0,0.760210,-0.000000

In [13]:
MB_CRS3 = MB_CRS.pivot_table(
    values=['OE',	'TE',	'PIAE',	'NPIAE',	'NPOAE'],
    index=dmuname,
    columns='year',
    aggfunc='mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
)    [['OE',	'TE',	'PIAE',	'NPIAE',	'NPOAE']]

In [14]:
MB_CRS3

            OE                            TE                     PIAE       \
year      2015      2016      2017      2015      2016      2017 2015 2016
省份
上海    0.031004  0.018273  0.000000  0.964068  0.940379  0.943613  1.0  1.0
云南    0.032409  0.000000  0.012322  0.527680  0.485824  0.475884  1.0  1.0
内蒙古   0.005232  0.006365  0.007179  0.697871  0.683949  0.683237  1.0  1.0
北京    0.000000  0.000000  0.000000  1.000000  1.000000  1.000000  1.0  1.0
吉林    0.000000  0.000000  0.000000  0.471377  0.475443  0.468917  1.0  1.0
四川    0.083117  0.120015  0.144551  0.630847  0.684221  0.699825  1.0  1.0
天津    0.000000  0.000000  0.000000  0.929002  0.946106  0.909456  1.0  1.0
宁夏    0.000000  0.000239  0.003284  0.870653  0.935367  0.820628  1.0  1.0
安徽    0.000000  0.000000  0.000000  0.893180  0.907960  0.925247  1.0  1.0
山东    0.014746  0.007639  0.008902  0.941141  1.000000  0.961953  1.0  1.0
山西    0.000000  0.000000  0.000000  0.812594  0.807216  0.771330  1.0  1.0
广东    0.000000  0.000000  0.000000  0.821981  0.824862  0.854480  1.0  1.0
广西    0.000000  0.000000  0.003472  0.647240  0.622971  0.617619  1.0  1.0
新疆    0.000000  0.000000  0.000000  0.857675  0.835614  0.821106  1.0  1.0
江苏    0.000000  0.000000  0.000000  0.979908  1.000000  1.000000  1.0  1.0
江西    0.011499  0.000000  0.000000  0.705820  0.836494  0.862645  1.0  1.0
河北    0.135243  0.151460  0.166044  0.908793  0.899910  1.000000  1.0  1.0
河南    0.000000  0.000000  0.000000  0.797030  0.776908  0.791257  1.0  1.0
浙江    0.000000  0.000000  0.000000  1.000000  1.000000  1.000000  1.0  1.0
海南    0.000000  0.000000  0.000000  0.980608  0.800122  0.746078  1.0  1.0
湖北    0.032364  0.028567  0.007716  0.734155  0.755342  0.777140  1.0  1.0
湖南    0.018901  0.097623  0.098146  0.689327  0.713410  0.734379  1.0  1.0
甘肃    0.000000  0.000000  0.000000  0.677079  0.682910  0.666668  1.0  1.0
福建    0.000000  0.000000  0.000000  0.833245  0.787048  0.828111  1.0  1.0
贵州    0.000000  0.000000  0.000000  0.819299  0.832390  0.835626  1.0  1.0
辽宁    0.044763  0.052623  0.036514  0.668295  0.703014  0.684614  1.0  1.0
重庆    0.000000  0.000000  0.000000  0.751821  0.723036  0.742940  1.0  1.0
陕西    0.000000  0.000000  0.000000  0.917689  0.960631  0.961040  1.0  1.0
青海    0.000000  0.000000  0.000000  0.594048  0.690198  0.657511  1.0  1.0
黑龙江   0.000000  0.000000  0.000000  0.567206  0.548421  0.542546  1.0  1.0

              NPIAE                         NPOAE
year 2017      2015      2016      2017      2015      2016      2017
省份
上海    1.0  0.777020  0.777552  0.759212  0.041388  0.024991  0.000000
云南    1.0  1.000000  1.000000  1.000000  0.061417  0.000000  0.025893
内蒙古   1.0  0.759861  0.768336  0.756741  0.009866  0.012111  0.013885
北京    1.0  0.979755  0.999656  1.000000  0.000000  0.000000  0.000000
吉林    1.0  1.000000  1.000000  0.995028  0.000000  0.000000  0.000000
四川    1.0  1.000000  1.000000  1.000000  0.131755  0.175404  0.206553
天津    1.0  0.761213  0.766140  0.772754  0.000000  0.000000  0.000000
宁夏    1.0  0.730112  0.753031  0.744451  0.000000  0.000339  0.005376
安徽    1.0  0.777038  0.770951  0.755448  0.000000  0.000000  0.000000
山东    1.0  0.746130  0.727224  0.770852  0.020999  0.010505  0.012005
山西    1.0  0.776656  0.780629  0.773225  0.000000  0.000000  0.000000
广东    1.0  0.846570  0.847264  0.811921  0.000000  0.000000  0.000000
广西    1.0  1.000000  1.000000  0.999914  0.000000  0.000000  0.005622
新疆    1.0  0.750504  0.758858  0.760210  0.000000  0.000000  0.000000
江苏    1.0  0.742164  0.728928  0.714219  0.000000  0.000000  0.000000
江西    1.0  0.978904  0.847401  0.802043  0.016644  0.000000  0.000000
河北    1.0  0.783236  0.788324  0.724755  0.190002  0.213498  0.229104
河南    1.0  0.847744  0.858678  0.850379  0.000000  0.000000  0.000000
浙江    1.0  0.760612  0.761281  0.757532  0.000000  0.000000  0.000000
海南    1.0  0.769098  0.840424  0.821716  0.000000  0.000000  0.000000
湖北    1.0  0.963361  0.956263  0.932844  0.045760  0.039549  0.010643
湖南    1.0  1.000000  1.000000  0.999872  0.027419  0.136840  0.133662
甘肃    1.0  0.994033  0.998465  0.999801  0.000000  0.000000  0.000000
福建    1.0  0.815669  0.839739  0.806632  0.000000  0.000000  0.000000
贵州    1.0  0.901209  0.877935  0.818457  0.000000  0.000000  0.000000
辽宁    1.0  0.852885  0.841416  0.831205  0.078534  0.088961  0.064167
重庆    1.0  0.896678  0.877672  0.866361  0.000000  0.000000  0.000000
陕西    1.0  0.797753  0.785499  0.773886  0.000000  0.000000  0.000000
青海    1.0  0.987354  0.953515  0.964655  0.000000  0.000000  0.000000
黑龙江   1.0  0.999874  0.999897  0.999934  0.000000  0.000000  0.000000

In [15]:
MB_CRS3[['OE']].to_markdown("MB_CRS_1.md")

MB_CRS3[['TE','PIAE']].to_markdown("MB_CRS_23.md")

MB_CRS3[['NPIAE','NPOAE']].to_markdown("MB_CRS_45.md")